#!/usr/bin/env ruby
# Target of this script: Convert a file of lexems list to a file of AST

require 'json'
require_relative 'lib/cli.rb'
require_relative 'lib/parser.rb'

# Parse CLI arguments

cli = Cli.new(
  extension: 'lex.json',
  util: 'parser',
)

# Make the AST from lexems list
if f = File.new("#{cli.source_path}/#{cli.source_name}.#{cli.source_extension}", 'r')
  parser = Parser.new(
    debug: !!cli.params.keys.include?('DEBUG'),
    lexems: JSON.parse(f.read).map{|r| Hash[r.map{|k,v| [k.to_sym, v]}] },
    source_name: cli.source_name,
  )

  parser.parse

  f.close
else
  puts "❗️ Can't read the source file '#{cli.source_path}'"
  exit
end # if

# Save the AST to JSON file

if f = File.new("#{cli.destination_path}/#{cli.source_name}.ast.json", 'w')
  f.puts(JSON.generate(parser.types))
  f.close
else
  puts "❗️ Can't save the AST file '#{cli.destination_path}/#{cli.source_name}.ast.json'"
  exit
end # if
