#!/usr/bin/env ruby
# Target of this script: Convert a file with AST to a file with C code

require 'json'
require_relative 'lib/cli.rb'
require_relative 'lib/c_compiler.rb'

# Parse CLI arguments

cli = Cli.new(
  extension: 'ast.json',
  util: 'translator',
)

# Make a list of lexems
if f = File.new("#{cli.source_path}/#{cli.source_name}.#{cli.source_extension}", 'r')
  compiler = CCompiler.new(ast: JSON.parse(f.read))
  # puts '--- AST BEGIN ---'
  # puts JSON.generate(compiler.ast)
  # puts '--- AST END ---'
  compiler.parse(compiler.ast)
  f.close
else
  puts "❗️ Can't read the AST file '#{cli.source_path}'"
  exit
end # if

# Save C code
if f = File.new("#{cli.destination_path}/#{cli.source_name}.c", 'w')
  f.puts(compiler.compile)
  f.close
else
  puts "❗️ Can't save C file '#{cli.destination_path}/#{cli.source_name}.c'"
  exit
end # if
